version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Yxop86HBw1c0'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
  flexibledata-core:
    image: chandimal/flexibledata:0.1
    ports:
      - '8081:80'
    env_file:
      - core-variables.env
    depends_on:
      - db
